name: prototype
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  provider: ^6.0.5
  http: ^1.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.3
  equatable: ^2.0.7
  crypto: ^3.0.0
  fl_chart: ^0.69.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.3.3
  equatable: ^2.0.7
  crypto: ^3.0.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Audiowide
      fonts:
        - asset: fonts/Fugaz_One/Fugaz_One/FugazOne-Regular.ttf